// spanish_full_vocab.js
// Merged from existing file + "Spanish Learning Glossary.docx"
// Rules: Categories stay capitalized; english/spanish lowercased; phonetic keeps capitalization from source (parentheses removed).
window.SPANISH_DATA = {
  "Basics": [
    { "english": "and", "spanish": "y", "phonetic": "ee" },
    { "english": "or", "spanish": "o", "phonetic": "oh" },
    { "english": "but", "spanish": "pero", "phonetic": "PEH-roh" },
    { "english": "because", "spanish": "porque", "phonetic": "POR-keh" },
    { "english": "also, too", "spanish": "también", "phonetic": "tahm-BYEN" },

    { "english": "what?", "spanish": "¿qué?", "phonetic": "keh?" },
    { "english": "who?", "spanish": "¿quién?", "phonetic": "kyehn?" },
    { "english": "where?", "spanish": "¿dónde?", "phonetic": "DON-deh?" },
    { "english": "when?", "spanish": "¿cuándo?", "phonetic": "KWAN-doh?" },
    { "english": "why?", "spanish": "¿por qué?", "phonetic": "por KEH?" },
    { "english": "how?", "spanish": "¿cómo?", "phonetic": "KOH-moh?" },
    { "english": "which?, which one?", "spanish": "¿cuál?", "phonetic": "kwahl?" },
    { "english": "how much?", "spanish": "¿cuánto, cuánta?", "phonetic": "KWAN-toh, KWAHN-tah" },
    { "english": "how many?", "spanish": "¿cuántos, cuántas?", "phonetic": "KWAN-tohs, KWAHN-tahs" },
    { "english": "what time is it?", "spanish": "¿qué hora es?", "phonetic": "keh OH-rah ess?" },

    { "english": "now", "spanish": "ahora", "phonetic": "ah-OH-rah" },
    { "english": "after, later", "spanish": "después", "phonetic": "des-PWEHS" },
    { "english": "before", "spanish": "antes", "phonetic": "AN-tess" },
    { "english": "early", "spanish": "temprano", "phonetic": "tem-PRAH-noh" },
    { "english": "late", "spanish": "tarde", "phonetic": "TAR-deh" },
    { "english": "here", "spanish": "aquí, acá", "phonetic": "ah-KEE, ah-KAH" },
    { "english": "there", "spanish": "allí, allá", "phonetic": "ah-YEE, ah-YAH" },
    { "english": "well", "spanish": "bien", "phonetic": "byen" },
    { "english": "badly, poorly", "spanish": "mal", "phonetic": "mahl" },
    { "english": "very", "spanish": "muy", "phonetic": "mooy" },
    { "english": "a lot, much", "spanish": "mucho", "phonetic": "MOO-choh" },
    { "english": "always", "spanish": "siempre", "phonetic": "SYEM-preh" },
    { "english": "never", "spanish": "nunca", "phonetic": "NOON-kah" },

    { "english": "be careful!", "spanish": "¡ten cuidado!", "phonetic": "ten kwee-DAH-doh!" },
    { "english": "watch out!", "spanish": "¡cuidado!", "phonetic": "kwee-DAH-doh!" },
    { "english": "behind you!", "spanish": "¡detrás de ti!", "phonetic": "deh-TRAHS deh tee!" },
    { "english": "are you okay? (informal)", "spanish": "¿estás bien?", "phonetic": "eh-STAHS byen?" },
    { "english": "are you okay? (formal)", "spanish": "¿está bien?", "phonetic": "eh-STAH byen?" },
    { "english": "good job!", "spanish": "¡buen trabajo!", "phonetic": "bwen trah-BAH-ho!" },
    { "english": "you're the best!", "spanish": "¡eres el mejor!", "phonetic": "EH-res el meh-HOR!" },
    { "english": "teamwork!", "spanish": "¡trabajo en equipo!", "phonetic": "trah-BAH-ho en eh-KEE-poh!" },
    { "english": "we're in this together.", "spanish": "estamos en esto juntos.", "phonetic": "eh-STA-mohs en ESS-toh HOON-tohs" },
    { "english": "let's do this!", "spanish": "¡vamos a hacerlo!", "phonetic": "VAH-mohs ah ah-SER-loh!" },
    { "english": "keep going", "spanish": "sigue así", "phonetic": "SEE-geh ah-SEE" },
    { "english": "don't give up", "spanish": "no te rindas", "phonetic": "NOH teh REEN-dahs" },
    { "english": "i believe in you", "spanish": "creo en ti", "phonetic": "KREH-oh en tee" },
    { "english": "keep practicing", "spanish": "sigue practicando", "phonetic": "SEE-geh prak-tee-KAN-doh" },
    { "english": "one word at a time", "spanish": "una palabra a la vez", "phonetic": "OO-nah pah-LAH-brah ah lah BEHS" },
    { "english": "consistency beats intensity", "spanish": "la constancia vence a la intensidad", "phonetic": "lah kohn-STAN-syah BEN-seh ah lah in-ten-see-DAD" },
    { "english": "mistakes are fuel", "spanish": "los errores son combustible", "phonetic": "lohs eh-ROH-rehs sohn kohm-boos-TEE-bleh" }
  ],

  "People": [
    { "english": "dudette", "spanish": "tía", "phonetic": "TEE-ah" },
    { "english": "dude, guy (spain)", "spanish": "tío", "phonetic": "TEE-oh" },
    { "english": "friend (masculine)", "spanish": "amigo", "phonetic": "ah-MEE-goh" },
    { "english": "friend (feminine)", "spanish": "amiga", "phonetic": "ah-MEE-gah" },
    { "english": "teammate (masculine)", "spanish": "compañero", "phonetic": "kom-pah-NYEH-roh" },
    { "english": "teammate (feminine)", "spanish": "compañera", "phonetic": "kom-pah-NYEH-rah" },
    { "english": "man (casual \"hey man\")", "spanish": "hombre", "phonetic": "OM-breh" },
    { "english": "sir, mr.", "spanish": "señor", "phonetic": "seh-NYOR" },
    { "english": "ma'am, mrs.", "spanish": "señora", "phonetic": "seh-NYOR-ah" },
    { "english": "miss", "spanish": "señorita", "phonetic": "seh-nyor-EE-tah" }
  ],

  "Places": [
    { "english": "the bathroom", "spanish": "el baño", "phonetic": "el BAH-nyoh" },
    { "english": "the restaurant", "spanish": "el restaurante", "phonetic": "el rehs-tow-RAHN-teh" },
    { "english": "the hotel", "spanish": "el hotel", "phonetic": "el oh-TEL" },
    { "english": "the street", "spanish": "la calle", "phonetic": "lah KAH-yeh" },
    { "english": "the market", "spanish": "el mercado", "phonetic": "el mer-KAH-doh" },
    { "english": "the city", "spanish": "la ciudad", "phonetic": "lah syoo-DAD" },
    { "english": "the town", "spanish": "el pueblo", "phonetic": "el PWEH-bloh" },
    { "english": "the countryside, rural area", "spanish": "el campo, la área rural", "phonetic": "el KAM-poh, lah AH-reh-ah roo-RAL" },
    { "english": "the suburbs", "spanish": "los suburbios", "phonetic": "lohs soo-BOOR-byohs" },
    { "english": "the coast", "spanish": "la costa", "phonetic": "lah KOS-tah" },
    { "english": "the beach", "spanish": "la playa", "phonetic": "lah PLAH-yah" },
    { "english": "the sea, the ocean", "spanish": "el mar, el océano", "phonetic": "el mar, el oh-SEH-ah-noh" },
    { "english": "the lake", "spanish": "el lago", "phonetic": "el LAH-goh" },
    { "english": "the river", "spanish": "el río", "phonetic": "el REE-oh" },
    { "english": "the mountain", "spanish": "la montaña", "phonetic": "lah mon-TAHN-yah" },
    { "english": "the forest", "spanish": "el bosque", "phonetic": "el BOS-keh" },
    { "english": "the jungle", "spanish": "la selva", "phonetic": "lah SEL-vah" },
    { "english": "the desert", "spanish": "el desierto", "phonetic": "el deh-SYER-toh" },
    { "english": "the island", "spanish": "la isla", "phonetic": "lah EES-lah" },
    { "english": "(outer) space", "spanish": "el espacio exterior", "phonetic": "el es-PAH-syoh eks-teh-ree-OR" },
    { "english": "the universe", "spanish": "el universo", "phonetic": "el oo-nee-VER-soh" },
    { "english": "the moon", "spanish": "la luna", "phonetic": "lah LOO-nah" },
    { "english": "the sun", "spanish": "el sol", "phonetic": "el SOHL" },
    { "english": "the stars", "spanish": "las estrellas", "phonetic": "lahs es-TRAY-yahs" }
  ],

  "Things": [
    { "english": "monday", "spanish": "el lunes", "phonetic": "el LOO-ness" },
    { "english": "tuesday", "spanish": "el martes", "phonetic": "el MAR-tess" },
    { "english": "wednesday", "spanish": "el miércoles", "phonetic": "el MYER-koh-less" },
    { "english": "thursday", "spanish": "el jueves", "phonetic": "el HWEH-bess" },
    { "english": "friday", "spanish": "el viernes", "phonetic": "el BYER-ness" },
    { "english": "saturday", "spanish": "el sábado", "phonetic": "el SAH-bah-doh" },
    { "english": "sunday", "spanish": "el domingo", "phonetic": "el doh-MEEN-goh" },

    { "english": "january", "spanish": "enero", "phonetic": "eh-NEH-roh" },
    { "english": "february", "spanish": "febrero", "phonetic": "feh-BREH-roh" },
    { "english": "march", "spanish": "marzo", "phonetic": "MAR-soh" },
    { "english": "april", "spanish": "abril", "phonetic": "ah-BREEL" },
    { "english": "may", "spanish": "mayo", "phonetic": "MAH-yoh" },
    { "english": "june", "spanish": "junio", "phonetic": "HOO-nyoh" },
    { "english": "july", "spanish": "julio", "phonetic": "HOO-lyoh" },
    { "english": "august", "spanish": "agosto", "phonetic": "ah-GOS-toh" },
    { "english": "september", "spanish": "septiembre", "phonetic": "sep-TYEM-breh" },
    { "english": "october", "spanish": "octubre", "phonetic": "ok-TOO-breh" },
    { "english": "november", "spanish": "noviembre", "phonetic": "noh-VYEM-breh" },
    { "english": "december", "spanish": "diciembre", "phonetic": "dee-SYEM-breh" },

    { "english": "spring", "spanish": "la primavera", "phonetic": "lah pree-mah-VEH-rah" },
    { "english": "summer", "spanish": "el verano", "phonetic": "el beh-RAH-noh" },
    { "english": "fall, autumn", "spanish": "el otoño", "phonetic": "el oh-TOH-nyoh" },
    { "english": "winter", "spanish": "el invierno", "phonetic": "el een-VYER-noh" },

    { "english": "yesterday", "spanish": "ayer", "phonetic": "ah-YER" },
    { "english": "today", "spanish": "hoy", "phonetic": "oy" },
    { "english": "tomorrow", "spanish": "mañana", "phonetic": "mah-NYAH-nah" },
    { "english": "the day after tomorrow", "spanish": "pasado mañana", "phonetic": "pah-SAH-doh mah-NYAH-nah" },

    { "english": "0", "spanish": "cero", "phonetic": "SEH-roh" },
    { "english": "1", "spanish": "uno", "phonetic": "OO-noh" },
    { "english": "2", "spanish": "dos", "phonetic": "dohs" },
    { "english": "3", "spanish": "tres", "phonetic": "tress" },
    { "english": "4", "spanish": "cuatro", "phonetic": "KWAH-troh" },
    { "english": "5", "spanish": "cinco", "phonetic": "SEEN-koh" },
    { "english": "6", "spanish": "seis", "phonetic": "says" },
    { "english": "7", "spanish": "siete", "phonetic": "SYEH-teh" },
    { "english": "8", "spanish": "ocho", "phonetic": "OH-choh" },
    { "english": "9", "spanish": "nueve", "phonetic": "NWEH-veh" },
    { "english": "10", "spanish": "diez", "phonetic": "DYEHS" },
    { "english": "11", "spanish": "once", "phonetic": "OHN-seh" },
    { "english": "12", "spanish": "doce", "phonetic": "DOH-seh" },
    { "english": "13", "spanish": "trece", "phonetic": "TREH-seh" },
    { "english": "14", "spanish": "catorce", "phonetic": "kah-TOR-seh" },
    { "english": "15", "spanish": "quince", "phonetic": "KEEN-seh" },
    { "english": "16", "spanish": "dieciséis", "phonetic": "dyeh-see-SAYS" },
    { "english": "17", "spanish": "diecisiete", "phonetic": "dyeh-see-SYEH-teh" },
    { "english": "18", "spanish": "dieciocho", "phonetic": "dyeh-see-OH-choh" },
    { "english": "19", "spanish": "diecinueve", "phonetic": "dyeh-see-NWEH-veh" },
    { "english": "20", "spanish": "veinte", "phonetic": "BAYN-teh" },
    { "english": "21", "spanish": "veintiuno", "phonetic": "bayn-tee-OO-noh" },
    { "english": "22", "spanish": "veintidós", "phonetic": "bayn-tee-DOHS" },
    { "english": "23", "spanish": "veintitrés", "phonetic": "bayn-tee-TRESS" },
    { "english": "24", "spanish": "veinticuatro", "phonetic": "bayn-tee-KWAH-troh" },
    { "english": "25", "spanish": "veinticinco", "phonetic": "bayn-tee-SEEN-koh" },
    { "english": "26", "spanish": "veintiséis", "phonetic": "bayn-tee-SAYS" },
    { "english": "27", "spanish": "veintisiete", "phonetic": "bayn-tee-SYEH-teh" },
    { "english": "28", "spanish": "veintiocho", "phonetic": "bayn-tee-OH-choh" },
    { "english": "29", "spanish": "veintinueve", "phonetic": "bayn-tee-NWEH-veh" },
    { "english": "30", "spanish": "treinta", "phonetic": "TRAIN-tah" },
    { "english": "31", "spanish": "treinta y uno", "phonetic": "TRAIN-tah ee OO-noh" },
    { "english": "40", "spanish": "cuarenta", "phonetic": "kwah-REN-tah" },
    { "english": "50", "spanish": "cincuenta", "phonetic": "seen-KWEN-tah" },
    { "english": "60", "spanish": "sesenta", "phonetic": "seh-SEN-tah" }
  ],

  "Adjectives": [
    { "english": "kind", "spanish": "amable", "phonetic": "ah-MAH-bleh" },
    { "english": "nice, mean", "spanish": "simpático, simpática, antipático, antipática", "phonetic": "seem-PAH-tee-koh, seem-PAH-tee-kah, an-tee-PAH-tee-koh, an-tee-PAH-tee-kah" },
    { "english": "funny", "spanish": "gracioso, graciosa", "phonetic": "grah-SYOH-soh, grah-SYOH-sah" },
    { "english": "smart", "spanish": "inteligente", "phonetic": "een-teh-lee-HEN-teh" },
    { "english": "hard-working, lazy", "spanish": "trabajador, trabajadora, perezoso, perezosa", "phonetic": "trah-bah-hah-DOR, trah-bah-hah-DORAH, peh-reh-SOH-soh, peh-reh-SOH-sah" },
    { "english": "patient, impatient", "spanish": "paciente, impaciente", "phonetic": "pah-SYEN-teh, eem-pah-SYEN-teh" },
    { "english": "brave", "spanish": "valiente", "phonetic": "bah-LYEN-teh" },
    { "english": "generous, selfish", "spanish": "generoso, generosa, egoísta", "phonetic": "heh-neh-ROH-soh, heh-neh-ROH-sah, eh-goh-EES-tah" },
    { "english": "serious", "spanish": "serio, seria", "phonetic": "SEH-ryoh, SEH-ryah" },
    { "english": "shy", "spanish": "tímido, tímida", "phonetic": "TEE-mee-doh, TEE-mee-dah" },
    { "english": "happy, content", "spanish": "feliz, contento, contenta", "phonetic": "feh-LEES, kon-TEN-toh, kon-TEN-tah" },
    { "english": "sad", "spanish": "triste", "phonetic": "TREES-teh" },
    { "english": "angry", "spanish": "enojado, enojada", "phonetic": "eh-noh-HAH-doh, eh-noh-HAH-dah" },
    { "english": "excited", "spanish": "emocionado, emocionada", "phonetic": "eh-moh-syoh-NAH-doh, eh-moh-syoh-NAH-dah" },
    { "english": "tired", "spanish": "cansado, cansada", "phonetic": "kan-SAH-doh, kan-SAH-dah" },
    { "english": "scared", "spanish": "asustado, asustada", "phonetic": "ah-soos-TAH-doh, ah-soos-TAH-dah" },
    { "english": "nervous", "spanish": "nervioso, nerviosa", "phonetic": "ner-BYOH-soh, ner-BYOH-sah" },
    { "english": "surprised", "spanish": "sorprendido, sorprendida", "phonetic": "sor-pren-DEE-doh, sor-pren-DEE-dah" },
    { "english": "bored", "spanish": "aburrido, aburrida", "phonetic": "ah-boo-REE-doh, ah-boo-REE-dah" },
    { "english": "good, bad", "spanish": "bueno, buena, malo, mala", "phonetic": "BWEH-noh, BWEH-nah, MAH-loh, MAH-lah" },
    { "english": "big, small", "spanish": "grande, pequeño, pequeña", "phonetic": "GRAN-deh, peh-KEHN-yoh, peh-KEHN-yah" },
    { "english": "long, short", "spanish": "largo, larga, corto, corta", "phonetic": "LAR-goh, LAR-gah, KOR-toh, KOR-tah" },
    { "english": "pretty, ugly", "spanish": "bonito, bonita, feo, fea", "phonetic": "boh-NEE-toh, boh-NEE-tah, FEH-oh, FEH-ah" },
    { "english": "young, old", "spanish": "joven, viejo, vieja", "phonetic": "HOH-ben, BYEH-hoh, BYEH-hah" },
    { "english": "expensive, cheap", "spanish": "caro, cara, barato, barata", "phonetic": "KAH-roh, KAH-rah, bah-RAH-toh, bah-RAH-tah" },
    { "english": "hot, cold", "spanish": "caliente, frío, fría", "phonetic": "kah-LYEN-teh, FREE-oh, FREE-ah" },
    { "english": "clean, dirty", "spanish": "limpio, limpia, sucio, sucia", "phonetic": "LEEM-pyoh, LEEM-pyah, SOO-syoh, SOO-syah" },
    { "english": "full, empty", "spanish": "lleno, llena, vacío, vacía", "phonetic": "YEH-noh, YEH-nah, bah-SEE-oh, bah-SEE-ah" },
    { "english": "new, old", "spanish": "nuevo, nueva, viejo, vieja", "phonetic": "NWEH-boh, NWEH-bah, BYEH-hoh, BYEH-hah" },
    { "english": "modern, ancient", "spanish": "moderno, moderna, antiguo, antigua", "phonetic": "moh-DER-noh, moh-DER-nah, an-TEE-gwoh, an-TEE-gwah" },
    { "english": "hard, soft", "spanish": "duro, dura, blando, blanda", "phonetic": "DOO-roh, DOO-rah, BLAN-doh, BLAN-dah" },
    { "english": "heavy, light", "spanish": "pesado, pesada, ligero, ligera", "phonetic": "peh-SAH-doh, peh-SAH-dah, lee-HEH-roh, lee-HEH-rah" },
    { "english": "fast, slow", "spanish": "rápido, rápida, lento, lenta", "phonetic": "RAH-pee-doh, RAH-pee-dah, LEN-toh, LEN-tah" },
    { "english": "dangerous, safe", "spanish": "peligroso, peligrosa, seguro, segura", "phonetic": "peh-lee-GROH-soh, peh-lee-GROH-sah, seh-GOO-roh, seh-GOO-rah" },
    { "english": "useful, useless", "spanish": "útil, inútil", "phonetic": "OO-teel, ee-NOO-teel" },
    { "english": "broken", "spanish": "roto, rota", "phonetic": "ROH-toh, ROH-tah" },
    { "english": "public, private", "spanish": "público, pública, privado, privada", "phonetic": "POO-blee-koh, POO-blee-kah, pree-VAH-doh, pree-VAH-dah" },
    { "english": "quiet, noisy", "spanish": "tranquilo, tranquila, ruidoso, ruidosa", "phonetic": "trahn-KEE-loh, trahn-KEE-lah, rwee-DOH-soh, rwee-DOH-sah" },
    { "english": "natural", "spanish": "natural", "phonetic": "nah-too-RAL" },
    { "english": "beautiful", "spanish": "hermoso, hermosa", "phonetic": "er-MOH-soh, er-MOH-sah" },
    { "english": "delicious", "spanish": "delicioso, deliciosa", "phonetic": "deh-lee-SYOH-soh, deh-lee-SYOH-sah" },
    { "english": "sweet", "spanish": "dulce", "phonetic": "DOOL-seh" },
    { "english": "salty", "spanish": "salado, salada", "phonetic": "sah-LAH-doh, sah-LAH-dah" },
    { "english": "bitter", "spanish": "amargo, amarga", "phonetic": "ah-MAR-goh, ah-MAR-gah" },
    { "english": "spicy", "spanish": "picante", "phonetic": "pee-KAN-teh" },
    { "english": "sour", "spanish": "agrio, agria", "phonetic": "AH-gree-oh, AH-gree-ah" },
    { "english": "disgusting", "spanish": "asqueroso, asquerosa", "phonetic": "ahs-keh-ROH-soh, ahs-keh-ROH-sah" },
    { "english": "sunny", "spanish": "soleado, soleada", "phonetic": "soh-lye-AH-doh, soh-lye-AH-dah" },
    { "english": "cloudy", "spanish": "nublado, nublada", "phonetic": "noo-BLAH-doh, noo-BLAH-dah" },
    { "english": "rainy", "spanish": "lluvioso, lluviosa", "phonetic": "yoo-BYOH-soh, yoo-BYOH-sah" },
    { "english": "windy", "spanish": "ventoso, ventosa", "phonetic": "ben-TOH-soh, ben-TOH-sah" }
  ],

  "Verbs": [
    { "english": "i move", "spanish": "yo muevo", "phonetic": "MWEH-boh" },
    { "english": "you move", "spanish": "tú mueves", "phonetic": "MWEH-behs" },
    { "english": "he moves, she moves, you move (formal)", "spanish": "él mueve, ella mueve, usted mueve", "phonetic": "MWEH-beh" },
    { "english": "we move", "spanish": "nosotros movemos", "phonetic": "moh-BEH-mohs" },
    { "english": "you all move", "spanish": "vosotros movéis", "phonetic": "moh-BEHS" },
    { "english": "they move, you all move", "spanish": "ellos mueven, ellas mueven, ustedes mueven", "phonetic": "MWEH-ben" },

    { "english": "i clean", "spanish": "yo limpio", "phonetic": "LEEM-pyoh" },
    { "english": "you clean", "spanish": "tú limpias", "phonetic": "LEEM-pyahs" },
    { "english": "he cleans, she cleans, you clean (formal)", "spanish": "él limpia, ella limpia, usted limpia", "phonetic": "LEEM-pyah" },
    { "english": "we clean", "spanish": "nosotros limpiamos", "phonetic": "leem-PYAH-mohs" },
    { "english": "you all clean", "spanish": "vosotros limpiáis", "phonetic": "leem-PYAHS" },
    { "english": "they clean, you all clean", "spanish": "ellos limpian, ellas limpian, ustedes limpian", "phonetic": "LEEM-pyan" },

    { "english": "i crush", "spanish": "yo aplasto", "phonetic": "ah-PLAHS-toh" },
    { "english": "you crush", "spanish": "tú aplastas", "phonetic": "ah-PLAHS-tahs" },
    { "english": "he crushes, she crushes, you crush (formal)", "spanish": "él aplasta, ella aplasta, usted aplasta", "phonetic": "ah-PLAHS-tah" },
    { "english": "we crush", "spanish": "nosotros aplastamos", "phonetic": "ah-plah-STAH-mohs" },
    { "english": "you all crush", "spanish": "vosotros aplastáis", "phonetic": "ah-plah-STAHS" },
    { "english": "they crush, you all crush", "spanish": "ellos aplastan, ellas aplastan, ustedes aplastan", "phonetic": "ah-PLAHS-tan" },

    { "english": "i fold", "spanish": "yo doblo", "phonetic": "DOH-bloh" },
    { "english": "you fold", "spanish": "tú doblas", "phonetic": "DOH-blahs" },
    { "english": "he folds, she folds, you fold (formal)", "spanish": "él dobla, ella dobla, usted dobla", "phonetic": "DOH-blah" },
    { "english": "we fold", "spanish": "nosotros doblamos", "phonetic": "doh-BLAH-mohs" },
    { "english": "you all fold", "spanish": "vosotros dobláis", "phonetic": "doh-BLAHS" },
    { "english": "they fold, you all fold", "spanish": "ellos doblan, ellas doblan, ustedes doblan", "phonetic": "DOH-blan" },

    { "english": "i cut", "spanish": "yo corto", "phonetic": "KOR-toh" },
    { "english": "you cut", "spanish": "tú cortas", "phonetic": "KOR-tahs" },
    { "english": "he cuts, she cuts, you cut (formal)", "spanish": "él corta, ella corta, usted corta", "phonetic": "KOR-tah" },
    { "english": "we cut", "spanish": "nosotros cortamos", "phonetic": "kor-TAH-mohs" },
    { "english": "you all cut", "spanish": "vosotros cortáis", "phonetic": "kor-TAHS" },
    { "english": "they cut, you all cut", "spanish": "ellos cortan, ellas cortan, ustedes cortan", "phonetic": "KOR-tan" },

    { "english": "i empty", "spanish": "yo vacío", "phonetic": "bah-SEE-oh" },
    { "english": "you empty", "spanish": "tú vacías", "phonetic": "bah-SEE-ahs" },
    { "english": "he empties, she empties, you empty (formal)", "spanish": "él vacía, ella vacía, usted vacía", "phonetic": "bah-SEE-ah" },
    { "english": "we empty", "spanish": "nosotros vaciamos", "phonetic": "bah-SYAH-mohs" },
    { "english": "you all empty", "spanish": "vosotros vaciáis", "phonetic": "bah-SYAHS" },
    { "english": "they empty, you all empty", "spanish": "ellos vacían, ellas vacían, ustedes vacían", "phonetic": "bah-SEE-an" },

    { "english": "i unclog", "spanish": "yo desatasco", "phonetic": "deh-sah-TAHS-koh" },
    { "english": "you unclog", "spanish": "tú desatascas", "phonetic": "deh-sah-TAHS-kahs" },
    { "english": "he unclogs, she unclogs, you unclog (formal)", "spanish": "él desatasca, ella desatasca, usted desatasca", "phonetic": "deh-sah-TAHS-kah" },
    { "english": "we unclog", "spanish": "nosotros desatascamos", "phonetic": "deh-sah-tahs-KAH-mohs" },
    { "english": "you all unclog", "spanish": "vosotros desatascáis", "phonetic": "deh-sah-tahs-KAHS" },
    { "english": "they unclog, you all unclog", "spanish": "ellos desatascan, ellas desatascan, ustedes desatascan", "phonetic": "deh-sah-TAHS-kan" },

    { "english": "i help", "spanish": "yo ayudo", "phonetic": "ah-YOO-doh" },
    { "english": "you help", "spanish": "tú ayudas", "phonetic": "ah-YOO-dahs" },
    { "english": "he helps, she helps, you help (formal)", "spanish": "él ayuda, ella ayuda, usted ayuda", "phonetic": "ah-YOO-dah" },
    { "english": "we help", "spanish": "nosotros ayudamos", "phonetic": "ah-yoo-DAH-mohs" },
    { "english": "you all help", "spanish": "vosotros ayudáis", "phonetic": "ah-yoo-DAHS" },
    { "english": "they help, you all help", "spanish": "ellos ayudan, ellas ayudan, ustedes ayudan", "phonetic": "ah-YOO-dan" },

    { "english": "i speak", "spanish": "yo hablo", "phonetic": "AH-bloh" },
    { "english": "you speak", "spanish": "tú hablas", "phonetic": "AH-blahs" },
    { "english": "he speaks, she speaks, you speak (formal)", "spanish": "él habla, ella habla, usted habla", "phonetic": "AH-blah" },
    { "english": "we speak", "spanish": "nosotros hablamos", "phonetic": "ah-BLAH-mohs" },
    { "english": "you all speak", "spanish": "vosotros habláis", "phonetic": "ah-BLAHS" },
    { "english": "they speak, you all speak", "spanish": "ellos hablan, ellas hablan, ustedes hablan", "phonetic": "AH-blan" },

    { "english": "i understand", "spanish": "yo entiendo", "phonetic": "en-TYEN-doh" },
    { "english": "you understand", "spanish": "tú entiendes", "phonetic": "en-TYEN-dehs" },
    { "english": "he understands, she understands, you understand (formal)", "spanish": "él entiende, ella entiende, usted entiende", "phonetic": "en-TYEN-deh" },
    { "english": "we understand", "spanish": "nosotros entendemos", "phonetic": "en-ten-DEH-mohs" },
    { "english": "you all understand", "spanish": "vosotros entendéis", "phonetic": "en-ten-DEHS" },
    { "english": "they understand, you all understand", "spanish": "ellos entienden, ellas entienden, ustedes entienden", "phonetic": "en-TYEN-den" },

    { "english": "i know", "spanish": "yo sé", "phonetic": "seh" },
    { "english": "you know", "spanish": "tú sabes", "phonetic": "SAH-behs" },
    { "english": "he knows, she knows, you know (formal)", "spanish": "él sabe, ella sabe, usted sabe", "phonetic": "SAH-beh" },
    { "english": "we know", "spanish": "nosotros sabemos", "phonetic": "sah-BEH-mohs" },
    { "english": "you all know", "spanish": "vosotros sabéis", "phonetic": "sah-BEHS" },
    { "english": "they know, you all know", "spanish": "ellos saben, ellas saben, ustedes saben", "phonetic": "SAH-ben" },

    { "english": "i see", "spanish": "yo veo", "phonetic": "BEH-oh" },
    { "english": "you see", "spanish": "tú ves", "phonetic": "behs" },
    { "english": "he sees, she sees, you see (formal)", "spanish": "él ve, ella ve, usted ve", "phonetic": "beh" },
    { "english": "we see", "spanish": "nosotros vemos", "phonetic": "BEH-mohs" },
    { "english": "you all see", "spanish": "vosotros veis", "phonetic": "behs" },
    { "english": "they see, you all see", "spanish": "ellos ven, ellas ven, ustedes ven", "phonetic": "ben" },

    { "english": "i arrive", "spanish": "yo llego", "phonetic": "YEH-goh" },
    { "english": "you arrive", "spanish": "tú llegas", "phonetic": "YEH-gahs" },
    { "english": "he arrives, she arrives, you arrive (formal)", "spanish": "él llega, ella llega, usted llega", "phonetic": "YEH-gah" },
    { "english": "we arrive", "spanish": "nosotros llegamos", "phonetic": "yeh-GAH-mohs" },
    { "english": "you all arrive", "spanish": "vosotros llegáis", "phonetic": "yeh-GAHS" },
    { "english": "they arrive, you all arrive", "spanish": "ellos llegan, ellas llegan, ustedes llegan", "phonetic": "YEH-gan" },

    { "english": "i leave", "spanish": "yo salgo", "phonetic": "SAHL-goh" },
    { "english": "you leave", "spanish": "tú sales", "phonetic": "SAH-lehs" },
    { "english": "he leaves, she leaves, you leave (formal)", "spanish": "él sale, ella sale, usted sale", "phonetic": "SAH-leh" },
    { "english": "we leave", "spanish": "nosotros salimos", "phonetic": "sah-LEE-mohs" },
    { "english": "you all leave", "spanish": "vosotros salís", "phonetic": "sah-LEES" },
    { "english": "they leave, you all leave", "spanish": "ellos salen, ellas salen, ustedes salen", "phonetic": "SAH-len" },

    { "english": "i need", "spanish": "yo necesito", "phonetic": "neh-seh-SEE-toh" },
    { "english": "you need", "spanish": "tú necesitas", "phonetic": "neh-seh-SEE-tahs" },
    { "english": "he needs, she needs, you need (formal)", "spanish": "él necesita, ella necesita, usted necesita", "phonetic": "neh-seh-SEE-tah" },
    { "english": "we need", "spanish": "nosotros necesitamos", "phonetic": "neh-seh-see-TAH-mohs" },
    { "english": "you all need", "spanish": "vosotros necesitáis", "phonetic": "neh-seh-see-TAHS" },
    { "english": "they need, you all need", "spanish": "ellos necesitan, ellas necesitan, ustedes necesitan", "phonetic": "neh-seh-SEE-tan" },

    { "english": "i give", "spanish": "yo doy", "phonetic": "doy" },
    { "english": "you give", "spanish": "tú das", "phonetic": "dahs" },
    { "english": "he gives, she gives, you give (formal)", "spanish": "él da, ella da, usted da", "phonetic": "dah" },
    { "english": "we give", "spanish": "nosotros damos", "phonetic": "DAH-mohs" },
    { "english": "you all give", "spanish": "vosotros dais", "phonetic": "dahs" },
    { "english": "they give, you all give", "spanish": "ellos dan, ellas dan, ustedes dan", "phonetic": "dan" },

    { "english": "i use", "spanish": "yo uso", "phonetic": "OO-soh" },
    { "english": "you use", "spanish": "tú usas", "phonetic": "OO-sahs" },
    { "english": "he uses, she uses, you use (formal)", "spanish": "él usa, ella usa, usted usa", "phonetic": "OO-sah" },
    { "english": "we use", "spanish": "nosotros usamos", "phonetic": "oo-SAH-mohs" },
    { "english": "you all use", "spanish": "vosotros usáis", "phonetic": "oo-SAHS" },
    { "english": "they use, you all use", "spanish": "ellos usan, ellas usan, ustedes usan", "phonetic": "OO-san" },

    { "english": "i start", "spanish": "yo empiezo", "phonetic": "em-PYEH-soh" },
    { "english": "you start", "spanish": "tú empiezas", "phonetic": "em-PYEH-sahs" },
    { "english": "he starts, she starts, you start (formal)", "spanish": "él empieza, ella empieza, usted empieza", "phonetic": "em-PYEH-sah" },
    { "english": "we start", "spanish": "nosotros empezamos", "phonetic": "em-peh-SAH-mohs" },
    { "english": "you all start", "spanish": "vosotros empezáis", "phonetic": "em-peh-SAHS" },
    { "english": "they start, you all start", "spanish": "ellos empiezan, ellas empiezan, ustedes empiezan", "phonetic": "em-PYEH-san" },

    { "english": "i finish", "spanish": "yo termino", "phonetic": "ter-MEE-noh" },
    { "english": "you finish", "spanish": "tú terminas", "phonetic": "ter-MEE-nahs" },
    { "english": "he finishes, she finishes, you finish (formal)", "spanish": "él termina, ella termina, usted termina", "phonetic": "ter-MEE-nah" },
    { "english": "we finish", "spanish": "nosotros terminamos", "phonetic": "ter-mee-NAH-mohs" },
    { "english": "you all finish", "spanish": "vosotros termináis", "phonetic": "ter-mee-NAHS" },
    { "english": "they finish, you all finish", "spanish": "ellos terminan, ellas terminan, ustedes terminan", "phonetic": "ter-MEE-nan" },

    { "english": "i am (permanent)", "spanish": "yo soy", "phonetic": "soy" },
    { "english": "you are (permanent)", "spanish": "tú eres", "phonetic": "EH-rehs" },
    { "english": "he is, she is, you are (formal, permanent)", "spanish": "él es, ella es, usted es", "phonetic": "ehs" },
    { "english": "we are (permanent)", "spanish": "nosotros somos", "phonetic": "SOH-mohs" },
    { "english": "you all are (permanent)", "spanish": "vosotros sois", "phonetic": "sohs" },
    { "english": "they are, you all are (permanent)", "spanish": "ellos son, ellas son, ustedes son", "phonetic": "sohn" },

    { "english": "i am (temporary)", "spanish": "yo estoy", "phonetic": "eh-STOY" },
    { "english": "you are (temporary)", "spanish": "tú estás", "phonetic": "eh-STAHS" },
    { "english": "he is, she is, you are (formal, temporary)", "spanish": "él está, ella está, usted está", "phonetic": "eh-STAH" },
    { "english": "we are (temporary)", "spanish": "nosotros estamos", "phonetic": "eh-STAH-mohs" },
    { "english": "you all are (temporary)", "spanish": "vosotros estáis", "phonetic": "eh-STAHS" },
    { "english": "they are, you all are (temporary)", "spanish": "ellos están, ellas están, ustedes están", "phonetic": "eh-STAHN" },

    { "english": "i have", "spanish": "yo tengo", "phonetic": "TEN-goh" },
    { "english": "you have", "spanish": "tú tienes", "phonetic": "TYEH-nehs" },
    { "english": "he has, she has, you have (formal)", "spanish": "él tiene, ella tiene, usted tiene", "phonetic": "TYEH-neh" },
    { "english": "we have", "spanish": "nosotros tenemos", "phonetic": "teh-NEH-mohs" },
    { "english": "you all have", "spanish": "vosotros tenéis", "phonetic": "teh-NEHS" },
    { "english": "they have, you all have", "spanish": "ellos tienen, ellas tienen, ustedes tienen", "phonetic": "TYEH-nen" },

    { "english": "i go", "spanish": "yo voy", "phonetic": "boy" },
    { "english": "you go", "spanish": "tú vas", "phonetic": "bahs" },
    { "english": "he goes, she goes, you go (formal)", "spanish": "él va, ella va, usted va", "phonetic": "bah" },
    { "english": "we go", "spanish": "nosotros vamos", "phonetic": "BAH-mohs" },
    { "english": "you all go", "spanish": "vosotros vais", "phonetic": "bahs" },
    { "english": "they go, you all go", "spanish": "ellos van, ellas van, ustedes van", "phonetic": "bahn" },

    { "english": "i do", "spanish": "yo hago", "phonetic": "AH-goh" },
    { "english": "you do", "spanish": "tú haces", "phonetic": "AH-sehs" },
    { "english": "he does, she does, you do (formal)", "spanish": "él hace, ella hace, usted hace", "phonetic": "AH-seh" },
    { "english": "we do", "spanish": "nosotros hacemos", "phonetic": "ah-SEH-mohs" },
    { "english": "you all do", "spanish": "vosotros hacéis", "phonetic": "ah-SEHS" },
    { "english": "they do, you all do", "spanish": "ellos hacen, ellas hacen, ustedes hacen", "phonetic": "AH-sen" },

    { "english": "i can", "spanish": "yo puedo", "phonetic": "PWEH-doh" },
    { "english": "you can", "spanish": "tú puedes", "phonetic": "PWEH-dehs" },
    { "english": "he can, she can, you can (formal)", "spanish": "él puede, ella puede, usted puede", "phonetic": "PWEH-deh" },
    { "english": "we can", "spanish": "nosotros podemos", "phonetic": "poh-DEH-mohs" },
    { "english": "you all can", "spanish": "vosotros podéis", "phonetic": "poh-DEHS" },
    { "english": "they can, you all can", "spanish": "ellos pueden, ellas pueden, ustedes pueden", "phonetic": "PWEH-den" },

    { "english": "i want", "spanish": "yo quiero", "phonetic": "KYEH-roh" },
    { "english": "you want", "spanish": "tú quieres", "phonetic": "KYEH-rehs" },
    { "english": "he wants, she wants, you want (formal)", "spanish": "él quiere, ella quiere, usted quiere", "phonetic": "KYEH-reh" },
    { "english": "we want", "spanish": "nosotros queremos", "phonetic": "keh-REH-mohs" },
    { "english": "you all want", "spanish": "vosotros queréis", "phonetic": "keh-REHS" },
    { "english": "they want, you all want", "spanish": "ellos quieren, ellas quieren, ustedes quieren", "phonetic": "KYEH-ren" },

    { "english": "i say", "spanish": "yo digo", "phonetic": "DEE-goh" },
    { "english": "you say", "spanish": "tú dices", "phonetic": "DEE-sehs" },
    { "english": "he says, she says, you say (formal)", "spanish": "él dice, ella dice, usted dice", "phonetic": "DEE-seh" },
    { "english": "we say", "spanish": "nosotros decimos", "phonetic": "deh-SEE-mohs" },
    { "english": "you all say", "spanish": "vosotros decís", "phonetic": "deh-SEES" },
    { "english": "they say, you all say", "spanish": "ellos dicen, ellas dicen, ustedes dicen", "phonetic": "DEE-sen" },

    { "english": "i eat", "spanish": "yo como", "phonetic": "KOH-moh" },
    { "english": "you eat", "spanish": "tú comes", "phonetic": "KOH-mehs" },
    { "english": "he eats, she eats, you eat (formal)", "spanish": "él come, ella come, usted come", "phonetic": "KOH-meh" },
    { "english": "we eat", "spanish": "nosotros comemos", "phonetic": "koh-MEH-mohs" },
    { "english": "you all eat", "spanish": "vosotros coméis", "phonetic": "koh-MEHS" },
    { "english": "they eat, you all eat", "spanish": "ellos comen, ellas comen, ustedes comen", "phonetic": "KOH-men" },

    { "english": "i drink", "spanish": "yo bebo", "phonetic": "BEH-boh" },
    { "english": "you drink", "spanish": "tú bebes", "phonetic": "BEH-behs" },
    { "english": "he drinks, she drinks, you drink (formal)", "spanish": "él bebe, ella bebe, usted bebe", "phonetic": "BEH-beh" },
    { "english": "we drink", "spanish": "nosotros bebemos", "phonetic": "beh-BEH-mohs" },
    { "english": "you all drink", "spanish": "vosotros bebéis", "phonetic": "beh-BEHS" },
    { "english": "they drink, you all drink", "spanish": "ellos beben, ellas beben, ustedes beben", "phonetic": "BEH-ben" },

    { "english": "i buy", "spanish": "yo compro", "phonetic": "KOHM-proh" },
    { "english": "you buy", "spanish": "tú compras", "phonetic": "KOHM-prahs" },
    { "english": "he buys, she buys, you buy (formal)", "spanish": "él compra, ella compra, usted compra", "phonetic": "KOHM-prah" },
    { "english": "we buy", "spanish": "nosotros compramos", "phonetic": "kohm-PRAH-mohs" },
    { "english": "you all buy", "spanish": "vosotros compráis", "phonetic": "kohm-PRAHS" },
    { "english": "they buy, you all buy", "spanish": "ellos compran, ellas compran, ustedes compran", "phonetic": "KOHM-pran" },

    { "english": "i work", "spanish": "yo trabajo", "phonetic": "trah-BAH-hoh" },
    { "english": "you work", "spanish": "tú trabajas", "phonetic": "trah-BAH-hahs" },
    { "english": "he works, she works, you work (formal)", "spanish": "él trabaja, ella trabaja, usted trabaja", "phonetic": "trah-BAH-hah" },
    { "english": "we work", "spanish": "nosotros trabajamos", "phonetic": "trah-bah-HAH-mohs" },
    { "english": "you all work", "spanish": "vosotros trabajáis", "phonetic": "trah-bah-HAHS" },
    { "english": "they work, you all work", "spanish": "ellos trabajan, ellas trabajan, ustedes trabajan", "phonetic": "trah-BAH-han" },

    { "english": "i call", "spanish": "yo llamo", "phonetic": "YAH-moh" },
    { "english": "you call", "spanish": "tú llamas", "phonetic": "YAH-mahs" },
    { "english": "he calls, she calls, you call (formal)", "spanish": "él llama, ella llama, usted llama", "phonetic": "YAH-mah" },
    { "english": "we call", "spanish": "nosotros llamamos", "phonetic": "yah-MAH-mohs" },
    { "english": "you all call", "spanish": "vosotros llamáis", "phonetic": "yah-MAHS" },
    { "english": "they call, you all call", "spanish": "ellos llaman, ellas llaman, ustedes llaman", "phonetic": "YAH-man" }
  ]
};
